-- runtime/src/store/schema.sql
-- AUTO-APPLIED by src/store/sqlite.ts as the v1 migration step.
-- DO NOT edit this file by hand — this is v1's BYTE SOURCE (bundled
-- into SCHEMA_SQL_V1 by bundle-schema.mjs). M1-05 appended a v2
-- migration step inside sqlite.ts that re-creates the agents table
-- with BLOB columns for encrypted api_key / claim_token. Current DB
-- state after full migration: see sqlite.ts's "Current schema (v2)"
-- header comment.
--
-- Tracked via `PRAGMA user_version`. This file defines user_version = 1;
-- sqlite.ts's MIGRATIONS array brings it to 2.
--
-- OUT-OF-SCOPE for this file (DO NOT add here):
--   * notifications  — v1.1.1 durable event stream (M2 when broker lands)
--   * match_history  — M1-15 / M1-21
--   * schedules      — M1-15
--   * encrypted column DDL — lives in sqlite.ts's v2 migration step,
--     NOT here (mutating this file would break SCHEMA_SQL_V1's byte
--     identity and thus the v1 migration contract).
--
-- When adding a new migration in a later TED, APPEND a new migration
-- step to sqlite.ts's MIGRATIONS array; DO NOT mutate this file's v1
-- block. Past installs will keep their v1 body and only run the delta.

CREATE TABLE IF NOT EXISTS agents (
  id           TEXT NOT NULL PRIMARY KEY,             -- UUID v4 from server
  name         TEXT NOT NULL UNIQUE,                   -- Public agent name
  api_key      TEXT NOT NULL,                          -- v1 plaintext; v2 migration re-creates as BLOB
  claim_token  TEXT NOT NULL,                          -- v1 plaintext; v2 migration re-creates as BLOB
  model        TEXT NOT NULL DEFAULT '',
  created_at   INTEGER NOT NULL,                       -- unix ms
  updated_at   INTEGER NOT NULL                        -- unix ms
);

CREATE INDEX IF NOT EXISTS idx_agents_name ON agents(name);
